### ISSUE TITLE
resolve `base-pkg` error

### ISSUE THREAD

**Issue by ketzacoatl** [fpco/fpco-salt-formula#121]
I believe this is due to the list of packages being empty (by default).

```
----------
          ID: base-pkg
    Function: pkg.installed
      Result: False
     Comment: Problem encountered installing package(s). Additional info follows:
              
              errors:
                  - Running scope as unit run-r16bd205b18db437997152cd823f96ea6.scope.
                    E: Unable to locate package base-pkg
     Started: 10:52:03.628810
    Duration: 13174.586 ms
     Changes:  
```
