### ISSUE TITLE
why does nomad.service unit file have bootstrap expect 3?

### ISSUE THREAD

**Issue by ketzacoatl** [fpco/fpco-salt-formula#134]
In the vagrant setup, after applying `salt-call --local state.sls nomad.service`, the systemd unit file for nomad looks like:

```
# cat /etc/systemd/system/nomad.service                                                                                                              
[Unit]
Description=Nomad Server
Requires=network-online.target
After=network-online.target

[Service]
ExecStart=/usr/local/bin/nomad agent -server -config /etc/nomad/config -config /etc/nomad/conf.d/ -bootstrap-expect 3
Restart=on-failure

User=nomad
Group=nomad

[Install]
WantedBy=multi-user.target
```

For pillar, `/vagrant/tests/srv/pillar/bootstrap.sls` has:

```
nomad:
  net_if: enp0s3
  datacenter: vagrant
  bootstrap_expect: 1
  server: True
```
